SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `projetSGBD`.`ELEVE` ;
DROP TABLE IF EXISTS `projetSGBD`.`MEMBRE` ;
DROP TABLE IF EXISTS `projetSGBD`.`JEU` ;
DROP TABLE IF EXISTS `projetSGBD`.`EVENEMENT` ;
DROP TABLE IF EXISTS `projetSGBD`.`COMMENTAIRE` ;
DROP TABLE IF EXISTS `projetSGBD`.`LIVRE` ;
DROP TABLE IF EXISTS `projetSGBD`.`EXEMPLAIRE` ;
DROP TABLE IF EXISTS `projetSGBD`.`PARTICIPE` ;
DROP TABLE IF EXISTS `projetSGBD`.`UTILISE` ;
DROP TABLE IF EXISTS `projetSGBD`.`EMPRUNT` ;

DROP VIEW IF EXISTS `projetSGBD`.`HISTORIQUE_MEMBRE` ;
DROP TABLE IF EXISTS `projetSGBD`.`HISTORIQUE_MEMBRE`;

DROP VIEW IF EXISTS `projetSGBD`.`MEMBRE_ACTUEL` ;
DROP TABLE IF EXISTS `projetSGBD`.`MEMBRE_ACTUEL`;

DROP VIEW IF EXISTS `projetSGBD`.`LIVRE_EMPRUNTE` ;
DROP TABLE IF EXISTS `projetSGBD`.`LIVRE_EMPRUNTE`;


DROP TRIGGER IF EXISTS `projetSGBD`.`MULTIPLE_COMMENT` ;

SET FOREIGN_KEY_CHECKS=1;